mozilla/jetstream-config

.circleci/config.yml

Depends on https://github.com/mozilla/jetstream/pull/282
Fixes https://github.com/mozilla/jetstream-config/issues/12

Update CI config to rerun changed experiments with Jetstream Argo

---

bug-1671484-pref-validation-of-relpreload-performance-impact-release-82-83.toml

Fix column name

---

.circleci/config.yml

This should make CI feedback a little faster.

[ci skip] don't reinstall git

---

README.md

And fix the template strings, whoops.

[ci skip] Document date overrides

---

.circleci/config.yml

Fixes https://github.com/mozilla/jetstream-config/issues/32

CircleCI random pod identifiers

---

.circleci/config.yml

See https://github.com/mozilla/jetstream/issues/356

Add link to Redash dashboard

---

.circleci/config.yml

Depends on https://github.com/mozilla/jetstream/pull/383/files

Add --return-status flag for rerun-config-changed

---

README.md

[ci skip] Document bigger_is_better flag.

---

.circleci/config.yml

https://github.com/mozilla/jetstream/issues/384

Jetstream remove entrypoint script

---

README.md
set-default-as-first-screen-100-roll-out.toml

We'd like to skip analyzing this experiment.
Anna, can you confirm that's also your understanding of what will happen here?

Skip set-default-as-first-screen-100-roll-out

---

.circleci/config.yml

Depends on https://github.com/mozilla/jetstream/pull/509

Add --recreate-enrollments to CI rerun

---

.circleci/config.yml

Depends on https://github.com/mozilla/jetstream/pull/555

--recreate-enrollments flag

---

bug-1695026-pref-new-tab-modernized-ux-region-2-release-86-88.toml

https://experimenter.services.mozilla.com/experiments/new-tab-modernized-ux-region-2/

Adding in config for Germany Modernized UX Experiment

---

bug-1695015-pref-new-tab-modernized-ux-region-1-release-86-88.toml

https://experimenter.services.mozilla.com/experiments/new-tab-modernized-ux-region-1/

Adding in config for Spain Modernized UX Experiment: 

---

.circleci/config.yml

fixes https://github.com/mozilla/jetstream-config/issues/65

Fix jetstream rerun checks

---

.circleci/config.yml

Add some logging so I get an idea what's happening

Rerun check fixes

---

bug-1698297-pref-fission-m7-beta-experiment-beta-88-89.toml
outcomes/firefox_desktop/picture_in_picture.toml

Upped enrollment period to valid values.

Fission Beta Exp M7: engagement and memory metrics added. 

---

bug-1696829-pref-new-tab-default-content-existing-users-ca-release-86-88.toml
bug-1696831-pref-activity-stream-new-tab-default-content-existin-release-85-88.toml

https://jira.mozilla.com/browse/DS-1491

Adding Reduce Switching via Default Content existing users config files 

---

bug-1695794-pref-new-tab-modernized-ux-region-1-existing-users-e-release-86-88.toml
bug-1695815-pref-new-tab-modernized-ux-region-2-existing-users-d-release-86-88.toml

https://jira.mozilla.com/browse/DS-1490

Adding in New Tab Modernized UX existing users configs.

---

bug-1695015-pref-new-tab-modernized-ux-region-1-release-86-88.toml

Using  `browser.newtabpage.enabled` pref.

Adding in newtab switch metric

---

bug-1696829-pref-new-tab-default-content-existing-users-ca-release-86-88.toml
bug-1696831-pref-activity-stream-new-tab-default-content-existin-release-85-88.toml

Fixing `reference_branch` for experiments.

Reference branch incorrectly specified

---

README.md

Depends on https://github.com/mozilla/jetstream/pull/581

Add monthly analysis period to README example

---

bug-1698297-pref-fission-m7-beta-experiment-beta-88-89.toml

Issues with loading, due to huge number of weekly metrics. Removing daily to help out.

Reducing report size

---

bug-1689450-pref-pre-xul-skeleton-ui-startup-improvement-experimen-release-86-90.toml

We should probably reject unrecognized keys...

Actually apply metrics

---

bug-1712979-pref-fission-beta-90-experiment-beta-90-91.toml

metric it isn't a useful metric.
https://bugzilla.mozilla.org/show_bug.cgi?id=1713360#c16

Removing `checkerboard_severity_count_per_hour` 

---

bug-1712979-pref-fission-beta-90-experiment-beta-90-91.toml

`input_event_response_ms_parent`

Adding new metric to include parent process

---

outcomes/firefox_ios/default_browser.toml

For https://docs.google.com/document/d/1UHKm_ko0zl_Q31aNwQwux2GK3-00IuVm55DJZs9mh1U/edit#
This needs someone from DS to take a look at the metric definitions.

Add default_browser outcome for Firefox iOS

---

bug-1727420-pref-fission-beta-93-process-count-experiment-beta-93-93.toml

Will need to update this after launch on Sept 7th. https://experimenter.services.mozilla.com/experiments/fission-beta-93-process-count-experiment/

Fission Beta 93 Process Count

---

bug-1722551-pref-full-js-parsing-experiment-nightly-94-94.toml

This is for an analysis of the finished experiment at https://experimenter.services.mozilla.com/experiments/full-js-parsing-experiment/.  I've mostly copied the fission process count experiment since it has many of the probes and segments I'd also like to see.

Bug 1722551 Full JS Parsing Experiment

---

outcomes/firefox_desktop/pocket_newtab.toml

In response to:
https://mozilla.slack.com/archives/CF94YGE03/p1645205222794109?thread_ts=1645053081.671499&cid=CF94YGE03

Cast null values to zero for urlbar_handoff_search_count metric

---

outcomes/firefox_desktop/spotlight_engagement.toml

From conversation with @shell1

Updates spotlight outcome with better description

---

outcomes/firefox_desktop/firefox_suggest.toml

* Adds new revenue proxies
* fixes urlbar searches

update firefox suggest outcomes

---

CODEOWNERS
defaults/README.md
defaults/cfr_metrics.toml
defaults/fenix.toml
defaults/firefox_desktop.toml
defaults/firefox_ios.toml
defaults/focus_android.toml
defaults/focus_ios.toml
defaults/klar_android.toml
defaults/klar_ios.toml

For https://github.com/mozilla/jetstream/issues/1130

Move default configs for experiments

---

.scripts/generate_docs.py
.scripts/templates/default_config.md

fixes https://github.com/mozilla/jetstream/issues/1157

Show analysis periods for default configs

---

firefox-ios-inactive-tabs.toml

Configuration for the [inactive tabs experiment](https://docs.google.com/document/d/1f70cAJF-ima3gwLNTW0gq8GsNl9hiOk4NbQKsefGU2E/edit?usp=sharing)

Firefox iOS inactive tabs experiment config

---

.scripts/generate_docs.py

Fixes https://github.com/mozilla/jetstream/issues/1160

Fix missing default metrics in docs

---

defaults/firefox_desktop.toml

Depends on https://github.com/mozilla/mozanalysis/pull/151

move QCDOU definition to mozanalysis

---

rally-first-prompt-for-users-without-an-enrolled-study-2nd-stage-rollout.toml
rally-first-prompt-for-users-without-an-enrolled-study.toml

https://mozilla.slack.com/archives/C03JK372UF6/p1658851330248809

Skip rally experiments

---

.circleci/config.yml

Reverts mozilla/jetstream-config#257

Revert "install/use gke auth plugin"

---

.circleci/config.yml

Reverts mozilla/jetstream-config#259

Revert "Gke auth error"

---

.circleci/config.yml

Reverts mozilla/jetstream-config#261

Revert "fix GKE auth error"

---

persist-search-term-staged-rollout-phase-1.toml

Updated persist search term config file with new feature metrics

Persist search term custom config
