bug-1668861-pref-measure-set-to-default-adoption-impact-of-chang-release-81-83.toml
bug-1672227-pref-measure-set-to-default-adoption-impact-of-chang-release-81-83.toml

This configuration covers the two "set-default-browser" experiments ([1](https://experimenter.services.mozilla.com/experiments/measure-set-to-default-adoption-impact-of-changing-the-prompt-to-set-firefox-as-default-v2-win7/) and [2](https://experimenter.services.mozilla.com/experiments/measure-new-user-retention-impact-of-changing-the-prompt-to-set-firefox-as-default/)). They differ only in the OS (win7 vs win10) as "set-default-browser" has different behaviors on those two systems.
Notes:
* All the metrics (`was_ever_default_browser`, `was_never_default_browser`, and `retained`) are blatantly "copied" from other existing config files 😜
* No segments defined as we only enroll new users

Add set-default-browser experiments

---

bug-1669364-pref-verify-changing-location-service-providers-still-release-82-83.toml

@tdsmith, could you check this? I just want to make sure this makes sense. Our study is looking at the difference in location services and it's currently being reported as a histogram. I propose getting the mean of the histogram and I am including the country breakdown to see how well it performs on a per country basis. Is this what the config would be actually processed to do?

update geolocation to include country breakdown

---

README.md
outcomes/fenix/example_config.toml
outcomes/firefox_desktop/example_config.toml

This PR adds outcome snippet docs and also checks if I understand the specification correctly.
Basically, outcome snippets are like experiment configurations, except they do not have an `[experiment]` section and no analysis window specification for `metrics` (jetstream will compute them only for `weekly` and `overall` by default).
Closes https://github.com/mozilla/jetstream/issues/109.

Outcome snippets docs

---

bug-1698297-pref-fission-m7-beta-experiment-beta-88-89.toml
outcomes/firefox_desktop/picture_in_picture.toml

Used to determine viability of `data_sources.main_cleaned` as implemented. The purpose is to remove the session corresponding to enrollment, when Fission pref can be flipped on, but is not enabled until restart.

Initial POC config for Fission M7 Beta experiment

---

bug-1698297-pref-fission-m7-beta-experiment-beta-88-89.toml

Fixes the `Bad int64 value` errors
Fixes https://github.com/mozilla/jetstream/issues/601

Fix Fission content_process_max

---

bug-1698297-pref-fission-m7-beta-experiment-beta-88-89.toml

Removing KDE and eCDF estimates for crashes. Removing a set of metrics. Adding `content_shutdown` crashes.

All NULL Metrics blowing up stats. 

---

outcomes/firefox_desktop/newtab_visibility.toml

Add an outcome for New Tab visibility, i.e. whether users have taken actions to disable New Tab, and how much exposure to New Tab users have.
This is intended to be consistent with https://docs.google.com/document/d/1WvsQGzN-L5f6GDR6SGcuoNvoM03yTxBGlx9ouSqlEVk/edit#.

Newtab visibility outcome

---

bug-1689450-pref-pre-xul-skeleton-ui-startup-improvement-experimen-release-86-90.toml

Explore dropping nominally unenrolled clientId's.

Add "tagged uri count" metric

---

default-browser-adoption-experiment-release.toml

Mostly copied from the Nightly experiment except for the two metrics that moved to the default browser Outcome.

Add Fenix set-default release experiment

---

firefox-suggest-history-vs-offline.toml

Goals:
- Compute all metrics on both an enrollment and exposure basis
- Add a custom metric to count the number of searches performed through the urlbar
- Add custom metrics to count the number of selections of urlbar results of various types

Firefox Suggest experiment: history vs offline

---

firefox-suggest-history-vs-offline.toml

Hey @rebecca-burwei, I was just looking through the Jetstream logs and noticed that bootstap mean cannot be computed for unenrollments since those are boolean values. I think we have to use binomial instead? Which would be similar to what was done here: https://github.com/mozilla/jetstream-config/blob/2a80436205902ea89ab758ec3ed92546915ad4b8/reminder-set-firefox-as-default.toml#L45

Use binomial for unenroll statistic in firefox-suggest-history-vs-offline

---

bug-1722112-pref-fission-process-count-nightly-92-94.toml

I was able to track down the problem for why this was failing. Joining main_v4 and crash_v4 results in a large amount of rows, too many for BigQuery to handle. Since this experiment is only running on nightly, we have to filter on the nightly channel.
For the other experiments about to be launched this will need to be changed to beta.
cc @cpeterso

Use beta channel when querying crash table for bug-1722112-pref-fission-process-count-nightly-92-94

---

firefox-100-user-agent.toml

custom config for [this experiment](https://experimenter.services.mozilla.com/nimbus/firefox-100-user-agent)
This is my first time doing this, my major question is whether I need to explicitly add the [default metrics](https://github.com/mozilla/jetstream/blob/main/jetstream/config/default_metrics.toml) so that they will continue to be reported, or whether I could leave them out this config file.

add config for firefox-100-user-agent

---

bug-1726656-pref-tab-unloading-nightly-93-94.toml

This is a draft config for the [Tab Unloading experiment ](https://experimenter.services.mozilla.com/experiments/tab-unloading/) which should launch on Aug 31st.
I'm creating it as a draft since I wanted to get someone to sanity check it in advance.
However, once the experiment launches, I'll need to plug in the generated Normandy experiment slug where I put `<tbd>` and as the file name.

Tab Unload Experiment Config

---

outcomes/firefox_ios/default_browser.toml

Should fix the issue that no data is shown for `default_browser_card_go_to_settings_pressed` for the default-browser-onboarding experiment
cc @ksiegler1

Remove nulls for firefox iOS default browser

---

bug-1725055-pref-fission-release-92-experiment-release-92-92.toml

This is a draft config for the [Fission Release experiment ](https://experimenter.services.mozilla.com/experiments/fission-release-92-experiment/) which should launch on Sept 7th.
I'm creating it as a draft so it's available to quickly make the final changes and merge once the experiment launches. After launch, I'll need to plug in the generated Normandy experiment slug where I put `<tbd>` and as the file name.

[DRAFT] Fission Release Experiment.

---

outcomes/firefox_desktop/pocket_newtab.toml

I incorrectly copied over the `card_type` field from earlier metrics in this file. `status` is the correct field to use for disable-related metrics.

Fix bugs in Pocket New Tab metrics.

---

default-browser-winning-branch-extended-holdback-study-release.toml

The enrollments table has been previously created and will be reused for the entire experiment date range

Temporary config for default-browser-winning-branch-extended-holdback-study-release

---

outcomes/firefox_desktop/pocket_newtab.toml

The [default](https://experimenter.info/jetstream/statistics#available-statistics) outlier filtering for the `bootstrap_mean` statistic removes the top 1e-4% of users for that metric:
https://experimenter.info/jetstream/statistics#available-statistics
These two pref change metrics are quite rare (~20-40 users per day out of ~140k), so I am changing the outlier filtering to drop the top 1e-7% of users.
Relevant conversation:
https://mozilla.slack.com/archives/CF94YGE03/p1639075124254300

Update outlier filtering on New Tab pref change metrics

---

outcomes/firefox_desktop/spotlight_engagement.toml

This is my first shot at adding a jetstream outcome, so please help if I gotten something wrong. 
This adds the `impressions`, `clicks`, and `dismisses` events for spotlight from the `messaging_system.spotlight` data source.

[DS-1844] Adds Spotlight engagement outcome

---

outcomes/firefox_desktop/reader_mode.toml

Per [conversation](https://mozilla.slack.com/archives/CF94YGE03/p1643400475482699?thread_ts=1643397185.331509&cid=CF94YGE03) with Anna Scholtz, we believe the metrics are not showing up in automated analysis because they occur infrequently and all users with these metrics are getting filtered out by outlier filtering.
This PR updates the outlier filtering percentiles accordingly so we get some data here.

Update outlier filtering for certain Reader Mode metrics

---

outcomes/firefox_desktop/pocket_newtab.toml

The Pocket team would like to add a Nimbus metric that tracks the number of searches driven by the search bar on the New Tab page.

Add URL bar handoff search count metric to Pocket New Tab outcome

---

defaults/README.md
defaults/firefox_desktop.toml
defaults/messaging.toml

Depends on https://github.com/mozilla/jetstream/pull/1136, https://github.com/mozilla/jetstream/pull/1138 for validation and to rerun affected experiments

Add qualified_cumulative_days_of_use to default metrics

---

defaults/firefox_desktop.toml

This is related to https://github.com/mozilla/jetstream/pull/1139.
This doesn't actually change anything but updates the config file and causes active experiments to rerun.

Trigger rerun

---

firefox-ios-inactive-tabs.toml

Use ping time instead of submission timestamp on the join to avoid comparing timestamp generate on the client with timestamp from the server

Update segment query for Firefox iOS inactive tab experiment

---

outcomes/firefox_desktop/page_load_performance.toml

This adds a new outcome for "Page Load Performace" with performance and memory related page load metrics. It is based on https://github.com/mozilla/jetstream-config/blob/main/bug-1722551-pref-full-js-parsing-experiment-nightly-94-94.toml, however does not include the crash and engagement metrics. 
Are the crash and engagement metrics something that are generally interesting and looked at when running experiments that use this outcome? We could also create separate outcomes if they are only sometimes interesting.
cc @dpalmeiro @shell1

Add page load performance outcome

---

defaults/focus_android.toml

Glean data has been included in https://github.com/mozilla/bigquery-etl/pull/2682 for Focus, so now we can query `mobile_search_clients_daily_v1` to have the same search default metrics as the other mobile browsers.
This will be used in the upcoming Focus onboarding experiment.

Add search and ad clicks as default metrics for Focus for Android

---

firefox-android-sponsored-shortcuts-experiment.toml
firefox-ios-homepage-experiment-sponsored-shortcuts.TOML
firefox-ios-homepage-experiment-sponsored-shortcuts.toml

Merged these configs yesterday which failed (https://app.circleci.com/pipelines/github/mozilla/jetstream-config/963/workflows/d4519d0d-6817-4b59-b5a6-aa5f91e61260/jobs/1304/steps) but it doesn't seem like an analysis error...

Triggering a jetstream re-run after strange errors

---

CODEOWNERS
definitions/fenix.toml
definitions/firefox_desktop.toml
definitions/firefox_ios.toml
definitions/focus_android.toml
definitions/focus_ios.toml
definitions/functions.toml
definitions/klar_android.toml
definitions/klar_ios.toml

Moving definitions from mozanalysis into the `definitions/` directory. I opted to name it `definitions/` instead of `metrics/` since it also contains data source and segment definitions.
These definitions aren't used at the moment and still need to be verified by DS. But merging for now to run some integration tests.

Add mozanalysis definitions

---

definitions/README.md
definitions/fenix.toml
definitions/firefox_desktop.toml

I missed the `{{ }}` when using aggregate functions in the definitions.

Fix Jinja templating in definitions

---

total-cookie-protection-experiment-v103.toml

[Experiment brief](https://docs.google.com/document/d/1mOdg5vIZNulyYIwY_CQHBq-YpJwHtuBjbfzQUoaZhG0/edit#)
We are interested in adding a metric indicative of breakage of page loading, so we'll go with a subset of the error page events.

Error page metric for Fenix TCP experiment

---

task-continuity-sync-after-tab-change-rollout-60.toml

Analysis fails on this every day with a KilledWorker exception, likely because the experiment is too large. We will skip this experiment to help reduce daily error alert noise.

Skip bc analysis always fails

---

.circleci/config.yml
defaults/fenix.toml
defaults/firefox_ios.toml
defaults/focus_android.toml
defaults/focus_ios.toml
defaults/klar_android.toml
defaults/klar_ios.toml
definitions/fenix.toml
definitions/firefox_desktop.toml
definitions/firefox_ios.toml
definitions/focus_android.toml
definitions/focus_ios.toml
definitions/klar_android.toml
definitions/klar_ios.toml

We can remove the duplicate metric definitions now that jetstream picks them up from metric-hub

Migrate to metric-hub

---

defaults/firefox_desktop.toml
outcomes/firefox_desktop/defaults_and_os_integration.toml

This adds a general outcome and then includes `is_default_browser` as a guard-rail metric.
Based on a Slack conversation with @scholtzan, I believe that it's safe to include the default browser statistic in the defaults *and* in the outcome.
I'll note that this depends on the corresponding PR at https://github.com/mozilla/metric-hub/pull/14; AFAIK, there's no way to work on two parts of the system simultaneously.  (I have used the `--config-repos` option to test this locally.)

Add Desktop defaults

---

viewpoint-survey-beta-validation-control-fix.toml

Needed to set explicit enrollment_end_date for experiment from before this fix that we want to rerun.

add viewpoint-survey-beta-validation-control-fix config
